id: check-structural
version: "1.0.0"
name: Structural Check Tool
description: >
  The cdd_check_structural tool runs fast, deterministic checks on
  the contract system that require no AI interpretation. It is designed
  for CI pipelines where speed and cost matter. It checks for broken
  refs, schema validation errors, orphaned annotations, missing test
  coverage, and dependency integrity. The result is a pass/fail boolean
  with categorized lists of errors and warnings.

priority: must
domain: mcp-tools
tags: [mcp, ci, validation]

trigger:
  type: mcp-tool-call
  tool: cdd_check_structural

depends_on:
  - contract: contract-schema-validation
    reason: Schema validation is one of the structural checks.
  - contract: test-annotation-scanning
    reason: Orphaned annotation detection requires scanning test files.
  - contract: get-contract-health
    reason: >
      Uses the same underlying health data but formats it as a
      pass/fail result for CI.

behaviors:
  - id: check-broken-refs
    description: >
      Detects contracts that reference files which do not exist on disk.
    constraints:
      - Must check top-level refs, behaviors[].refs, and testing.fixtures
      - Broken refs are always errors (not warnings)
      - Each error must include the contract id and the missing file path

  - id: check-schema-validation
    description: >
      Detects contracts that do not conform to the CDD YAML schema.
    refs:
      - schema/contract.schema.json
    constraints:
      - Schema violations are always errors
      - Each error must include the contract id and specific validation failures

  - id: check-orphaned-annotations
    description: >
      Detects test annotations that reference contract ids which do not
      exist.
    constraints:
      - Orphaned annotations are always errors
      - Each error must include the file path, line number, and referenced contract id

  - id: check-missing-coverage
    description: >
      Detects contracts with zero linked tests.
    constraints:
      - Missing coverage severity is configurable (error or warning)
      - Default is warning
      - Each entry must include the contract id

  - id: check-dependency-integrity
    description: >
      Detects depends_on entries that reference contract ids which do
      not exist.
    constraints:
      - Broken dependencies are always errors
      - Each error must include the contract id and the missing dependency id

  - id: return-pass-fail
    description: >
      Returns a top-level pass boolean, plus categorized errors and
      warnings.
    constraints:
      - pass is true only when there are zero errors
      - Warnings do not affect the pass/fail result
      - Each issue must include type, contract_id (if applicable), file (if applicable), line (if applicable), and message
