id: find-related-contracts
version: "1.0.0"
name: Find Related Contracts Tool
description: >
  The cdd_find_related tool finds contracts that share structural
  relationships with a given contract. It reports shared refs, shared
  trigger types/sources, and dependency chains (direct or transitive).
  This tool provides the raw structural facts that an agent uses to
  reason about potential conflicts or side effects. The tool never
  interprets whether a relationship constitutes a conflict -- that is
  the agent's job.

priority: must
domain: mcp-tools
tags: [mcp, planning, conflict-detection]

trigger:
  type: mcp-tool-call
  tool: cdd_find_related

behaviors:
  - id: detect-shared-refs
    description: >
      Finds contracts that reference any of the same files as the
      queried contract.
    constraints:
      - Must compare all ref locations (top-level refs, behavior refs, testing fixtures)
      - Each result must list the specific shared files
      - A contract sharing refs with itself must not appear in results

  - id: detect-shared-triggers
    description: >
      Finds contracts with overlapping trigger configurations.
    constraints:
      - Trigger overlap is determined by matching trigger.type and any source-identifying fields (e.g., topic, endpoint)
      - Contracts with no trigger never appear as shared-trigger matches

  - id: detect-dependency-chains
    description: >
      Finds contracts connected through depends_on relationships, both
      direct and transitive.
    constraints:
      - Direct dependencies (A depends on B) must be reported
      - Reverse dependencies (B is depended on by A) must be reported
      - Transitive chains (A depends on B, B depends on C -- report C when querying A) must be reported
      - Circular dependencies must be detected and reported without causing infinite loops

  - id: not-found
    description: >
      When the contract_id does not exist, the tool returns a clear error.
    constraints:
      - The error must include the requested id
