id: review-changeset
version: "1.0.0"
name: Review Changeset Tool
description: >
  The cdd_review_changeset tool is a convenience tool that bundles the
  calls an agent would otherwise make sequentially during a CI review.
  Given a list of changed files and an optional diff, it returns all
  affected contracts with their full resolved context and linked tests.
  The agent then performs the semantic review and produces verdicts. The
  tool itself does no interpretation -- it assembles context efficiently.

priority: must
domain: mcp-tools
tags: [mcp, ci, review]

trigger:
  type: mcp-tool-call
  tool: cdd_review_changeset

depends_on:
  - contract: get-affected-contracts
    reason: >
      Uses affected-contract resolution to find which contracts care
      about the changed files.
  - contract: get-contract
    reason: >
      Resolves full contract content and refs for each affected contract.
  - contract: get-linked-tests
    reason: >
      Includes linked tests per contract so the agent can assess coverage.

behaviors:
  - id: return-affected-contracts
    description: >
      Returns the list of affected contracts in summary form.
    constraints:
      - Uses the same resolution logic as cdd_get_affected_contracts
      - Includes matched_refs for each contract

  - id: return-resolved-context
    description: >
      For each affected contract, includes the full contract content
      with all refs resolved (file contents included).
    constraints:
      - Equivalent to calling cdd_get_contract with resolve_refs true for each affected contract
      - Missing ref files must be indicated, not silently omitted

  - id: return-linked-tests
    description: >
      Returns a map of contract id to linked test list for each
      affected contract.
    constraints:
      - Uses the same scanning logic as cdd_get_linked_tests
      - Each test entry includes file, line, and test_name

  - id: handle-no-affected
    description: >
      When no contracts are affected by the changed files, returns
      empty results rather than an error.
    constraints:
      - An empty affected_contracts list is a valid, non-error response
