id: update-contract
version: "1.0.0"
name: Update Contract Tool
description: >
  The cdd_update_contract tool applies partial updates to an existing
  contract. Fields provided in the updates parameter overwrite existing
  values; fields not provided are left unchanged. The tool validates
  the resulting contract, generates a human-readable diff, and writes
  the updated file. If validation fails, the original file is left
  unchanged.

priority: must
domain: mcp-tools
tags: [mcp, lifecycle, write]

trigger:
  type: mcp-tool-call
  tool: cdd_update_contract

depends_on:
  - contract: contract-schema-validation
    reason: >
      The merged contract must pass schema validation before being written.
  - contract: filename-id-consistency
    reason: >
      If the id is changed, the filename must be updated to match.

behaviors:
  - id: merge-and-write
    description: >
      Merges the updates into the existing contract and writes the
      result.
    constraints:
      - Fields not present in updates must be preserved from the original
      - The merge is shallow for top-level fields -- providing a new behaviors list replaces the entire behaviors list
      - The response must include the file path

  - id: generate-diff
    description: >
      The response includes a human-readable diff showing what changed.
    constraints:
      - The diff must show old and new values for changed fields
      - Unchanged fields should not appear in the diff
      - The diff format must be readable by both humans and agents

  - id: reject-invalid
    description: >
      If the merged result fails schema validation, the original file
      is left unchanged and errors are returned.
    constraints:
      - The original file must not be modified on validation failure
      - All validation errors must be returned

  - id: require-prior-read
    description: >
      Before applying an update, the tool verifies that cdd_get_contract
      was called for this contract_id in the current session. If not, it
      returns an error instructing the caller to read the contract first.
    constraints:
      - The error must name the contract_id and instruct the caller to call cdd_get_contract before retrying
      - The original file must not be modified when this check fails

  - id: not-found
    description: >
      When the contract_id does not exist, the tool returns a clear error.
    constraints:
      - The error must suggest using cdd_create_contract instead

  - id: handle-id-change
    description: >
      If the updates include a new id, the old file is removed and a
      new file is created with the new name.
    constraints:
      - The old file must be deleted
      - The new file must use the new id as its filename
      - If a contract with the new id already exists, the operation fails and the original is left unchanged
